In [11]:
## move to directory where data is
using DelimitedFiles
using DataFrames
using CSV

In [30]:
#ords=readlines("Cox2.node_attrs")
ords=readdlm("Cox2.node_labels")

[X,Y]=1

19252×1 Array{Float64,2}:
 6.0
 7.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 ⋮  
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [31]:
ords

19252×1 Array{Float64,2}:
 6.0
 7.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 6.0
 ⋮  
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [14]:
df = CSV.read("Cox2.node_attrs", DataFrame,header=false)

19252×3 DataFrame
   Row │ Column1    Column2    Column3   
       │ Float64    Float64    Float64   
───────┼─────────────────────────────────
     1 │  3.35523    0.143395   1.08385
     2 │  2.09003    0.200695   0.491354
     3 │  1.18823   -0.454505   1.34265
     4 │  1.90263   -0.921605   2.43435
     5 │  3.24443   -0.536105   2.28135
     6 │ -0.267772  -0.529905   1.16775
     7 │  1.78253    0.785495  -0.777046
     8 │ -0.939372   0.369895   0.327054
     9 │ -2.32787    0.303795   0.179254
    10 │ -3.05227   -0.656005   0.890254
    11 │ -2.39897   -1.55671    1.73455
   ⋮   │     ⋮          ⋮          ⋮
 19243 │ -0.157044  -2.06355    2.57645
 19244 │  2.83736    2.85355   -0.263553
 19245 │  2.22476    3.87155   -2.43575
 19246 │  0.760256   0.088453  -3.82575
 19247 │  1.36576   -0.960247  -1.67415
 19248 │  3.69456   -1.33785    3.72495
 19249 │  5.29476   -0.200047   2.17755
 19250 │ -5.65034   -1.87235   -1.00255
 19251 │ -4.15814   -2.73125   -0.522653
 19252 │ -4.07294   -1.32855   -1.64385
                       19231 rows omitted

In [25]:
all_attrs = zeros(19252,3)

for i in 1:size(df,1)

    all_attrs[i,1] = df[i,"Column1"]
    all_attrs[i,2] = df[i,"Column2"]
    all_attrs[i,3] = df[i,"Column3"]

end

In [26]:
all_attrs

19252×3 Array{Float64,2}:
  3.35523    0.143395   1.08385 
  2.09003    0.200695   0.491354
  1.18823   -0.454505   1.34265 
  1.90263   -0.921605   2.43435 
  3.24443   -0.536105   2.28135 
 -0.267772  -0.529905   1.16775 
  1.78253    0.785495  -0.777046
 -0.939372   0.369895   0.327054
 -2.32787    0.303795   0.179254
 -3.05227   -0.656005   0.890254
 -2.39897   -1.55671    1.73455 
 -1.00997   -1.48541    1.87705 
  2.01963    2.14879   -1.00465 
  ⋮                             
 -2.41034    1.09345   -0.531053
 -2.59154   -2.19865    2.26235 
 -0.157044  -2.06355    2.57645 
  2.83736    2.85355   -0.263553
  2.22476    3.87155   -2.43575 
  0.760256   0.088453  -3.82575 
  1.36576   -0.960247  -1.67415 
  3.69456   -1.33785    3.72495 
  5.29476   -0.200047   2.17755 
 -5.65034   -1.87235   -1.00255 
 -4.15814   -2.73125   -0.522653
 -4.07294   -1.32855   -1.64385 

In [3]:
df_1 = CSV.read("Cox2.edges", DataFrame,header=false)
all_attrs = zeros(19252,3)

for i in 1:size(df,1)

    all_attrs[i,1] = df[i,"Column1"]
    all_attrs[i,2] = df[i,"Column2"]
    all_attrs[i,3] = df[i,"Column3"]

end



ArgumentError: ArgumentError: cannot parse "  3.355228, 0.143395, 1.083854" as Float64

In [35]:
df_edges = CSV.read("Cox2.edges", DataFrame,header=false);


In [36]:
df_edges

40578×2 DataFrame
   Row │ Column1  Column2 
       │ Int64    Int64   
───────┼──────────────────
     1 │       2        1
     2 │       5        1
     3 │      19        1
     4 │       1        2
     5 │       3        2
     6 │       7        2
     7 │       2        3
     8 │       4        3
     9 │       6        3
    10 │       3        4
    11 │       5        4
   ⋮   │    ⋮        ⋮
 40569 │   19225    19243
 40570 │   19226    19244
 40571 │   19227    19245
 40572 │   19229    19246
 40573 │   19230    19247
 40574 │   19232    19248
 40575 │   19233    19249
 40576 │   19238    19250
 40577 │   19238    19251
 40578 │   19238    19252
        40557 rows omitted